"""Base classes and shared utilities for entity primitives."""

import math
import re
from abc import ABCMeta
from typing import Annotated, Any, Literal

import pydantic as pd

from flow360_schema.framework.base_model import Flow360BaseModel
from flow360_schema.framework.bounding_box import BoundingBoxType
from flow360_schema.framework.entity.entity_base import EntityBase
from flow360_schema.framework.entity.geometric_types import Axis
from flow360_schema.framework.unique_list import UniqueStringList

BOUNDARY_FULL_NAME_WHEN_NOT_FOUND = "This boundary does not exist!!!"


def _get_generated_boundary_names(surface_name: str, volume_mesh_meta: dict[str, Any]) -> list[Any]:
    """
    Returns all the boundaries that are eventually generated by name matching in the volume mesh metadata.

    May return multiple boundaries when the original one is split into multiple boundaries.
    """
    full_boundary_names = []

    for zone_name, zone_meta in volume_mesh_meta["zones"].items():
        for existing_boundary_name in zone_meta["boundaryNames"]:
            pattern = re.escape(zone_name) + r"/(.*)"
            match = re.search(pattern, existing_boundary_name)
            if (match is not None and match.group(1) == surface_name) or existing_boundary_name == surface_name:
                full_boundary_names.append(existing_boundary_name)

    if not full_boundary_names:
        return [BOUNDARY_FULL_NAME_WHEN_NOT_FOUND]

    return full_boundary_names


def _check_axis_is_orthogonal(axis_pair: tuple[Axis, Axis]) -> tuple[Axis, Axis]:
    """Validate that two axes are orthogonal and return normalized pair."""
    a1 = tuple(float(x) for x in axis_pair[0])
    a2 = [float(x) for x in axis_pair[1]]

    dot_product = sum(x * y for x, y in zip(a1, a2, strict=False))
    if abs(dot_product) > 1e-3:
        raise ValueError(f"The two axes are not orthogonal, dot product is {dot_product}.")

    # Remove any residual projection onto axis_1 and re-normalize
    a2 = [a2[i] - dot_product * a1[i] for i in range(3)]
    norm = math.sqrt(sum(x * x for x in a2))
    a2 = [x / norm for x in a2]

    return (a1, tuple(a2))  # type: ignore[return-value]


def _auto_symmetric_plane_exists_from_bbox(
    *,
    global_bounding_box: BoundingBoxType,
    planar_face_tolerance: float,
) -> bool:
    """
    Determine whether automated farfield logic will generate a `symmetric` plane
    from global bounding box extents and planar-face tolerance.
    """
    y_min = global_bounding_box[0][1]
    y_max = global_bounding_box[1][1]
    tolerance = global_bounding_box.largest_dimension * planar_face_tolerance

    positive_half = abs(y_min) < tolerance < y_max
    negative_half = abs(y_max) < tolerance and y_min < -tolerance

    return positive_half or negative_half


OrthogonalAxes = Annotated[tuple[Axis, Axis], pd.AfterValidator(_check_axis_is_orthogonal)]


class SurfacePrivateAttributes(Flow360BaseModel):
    """Private attributes for Surface."""

    type_name: Literal["SurfacePrivateAttributes"] = pd.Field("SurfacePrivateAttributes", frozen=True)
    bounding_box: BoundingBoxType = pd.Field(description="Bounding box of the surface.")


class _VolumeEntityBase(EntityBase, metaclass=ABCMeta):
    """All volumetric entities should inherit from this class."""

    private_attribute_zone_boundary_names: UniqueStringList = pd.Field(
        UniqueStringList(),  # type: ignore[call-arg]
        frozen=True,
        description="Boundary names of the zone WITH the prepending zone name.",
    )
    private_attribute_full_name: str | None = pd.Field(None, frozen=True)

    def _is_volume_zone(self) -> bool:
        """This is not a zone if zone boundaries are not defined. For validation usage."""
        return self.private_attribute_zone_boundary_names is not None

    def _update_entity_info_with_metadata(self, volume_mesh_meta_data: dict[str, Any]) -> None:
        """
        Update the full name of zones once the volume mesh is done.
        e.g. rotating_cylinder --> rotatingBlock-rotating_cylinder

        TODO: This bridge function should be extracted from entity class after migration.
        Similar to translator pattern.
        """
        entity_name = self.name
        for zone_full_name, zone_meta in volume_mesh_meta_data["zones"].items():
            pattern = r"rotatingBlock-" + re.escape(entity_name)
            if entity_name == "__farfield_zone_name_not_properly_set_yet":
                # We have hardcoded name for farfield zone.
                pattern = r"stationaryBlock|fluid"
            match = re.search(pattern, zone_full_name)
            if match is not None or entity_name == zone_full_name:
                self._force_set_attr("private_attribute_full_name", zone_full_name)
                self._force_set_attr(
                    "private_attribute_zone_boundary_names",
                    UniqueStringList(items=zone_meta["boundaryNames"]),
                )
                break

    @property
    def full_name(self) -> str:
        """Gets the full name which includes the zone name"""
        if self.private_attribute_full_name is None:
            return self.name
        return self.private_attribute_full_name


class _SurfaceEntityBase(EntityBase, metaclass=ABCMeta):
    """All surface entities should inherit from this class."""

    private_attribute_full_name: str | None = pd.Field(None, frozen=True)

    def _update_entity_info_with_metadata(self, volume_mesh_meta_data: dict[str, Any]) -> list["EntityBase"] | None:
        """
        Update parent zone name once the volume mesh is done.

        Returns a list of newly-created split-surface copies when a geometry
        boundary is split during volume meshing, or None if no split occurred.

        TODO: This bridge function should be extracted from entity class after migration.
        Similar to translator pattern.
        """
        updated_boundary_names = _get_generated_boundary_names(self.name, volume_mesh_meta_data)

        self._force_set_attr("private_attribute_full_name", updated_boundary_names.pop(0))

        multiplication_result = []
        for new_boundary_name in updated_boundary_names:
            multiplication_result.append(
                self.copy(
                    update={
                        "name": new_boundary_name,
                        "private_attribute_full_name": new_boundary_name,
                    }
                )
            )

        return multiplication_result if multiplication_result else None

    @property
    def full_name(self) -> str:
        """Gets the full name which includes the zone name"""
        if self.private_attribute_full_name is None:
            return self.name
        return self.private_attribute_full_name
