"""
This module is flow360.
"""

import os

from numpy import pi

from . import global_exception_handler, units
from .accounts_utils import Accounts
from .cli import flow360
from .cloud.s3_utils import ProgressCallbackInterface
from .component import meshing
from .component.case import Case
from .component.case import CaseList as MyCases
from .component.flow360_params import solvers
from .component.flow360_params.boundaries import (
    FreestreamBoundary,
    HeatFluxWall,
    IsothermalWall,
    MassInflow,
    MassOutflow,
    NoSlipWall,
    PressureOutflow,
    RiemannInvariant,
    RotationallyPeriodic,
    SlidingInterfaceBoundary,
    SlipWall,
    SolidAdiabaticWall,
    SolidIsothermalWall,
    SubsonicInflow,
    SubsonicOutflowMach,
    SubsonicOutflowPressure,
    SupersonicInflow,
    SymmetryPlane,
    TranslationallyPeriodic,
    VelocityInflow,
    WallFunction,
)
from .component.flow360_params.flow360_output import (
    IsoSurfaceOutput,
    IsoSurfaces,
    MonitorOutput,
    Monitors,
    ProbeMonitor,
    Slice,
    SliceOutput,
    Slices,
    SurfaceIntegralMonitor,
    SurfaceOutput,
    Surfaces,
)
from .component.flow360_params.flow360_params import (
    ActuatorDisk,
    AeroacousticOutput,
    AirDensityTemperature,
    AirPressureTemperature,
    BETDisk,
    BETDiskChord,
    BETDiskSectionalPolar,
    BETDiskTwist,
    Boundaries,
    Flow360MeshParams,
    Flow360Params,
    ForcePerArea,
    FreestreamFromMach,
    FreestreamFromMachReynolds,
    FreestreamFromVelocity,
    Geometry,
    HeatEquationSolver,
    MeshBoundary,
    PorousMediumBox,
    SlidingInterface,
    TransitionModelSolver,
    UnvalidatedFlow360Params,
    UserDefinedDynamic,
    VolumeOutput,
    VolumeZones,
    ZeroFreestream,
    ZeroFreestreamFromVelocity,
    air,
)
from .component.flow360_params.initial_condition import (
    ExpressionInitialCondition,
    ModifiedRestartSolution,
)
from .component.flow360_params.solvers import (
    IncompressibleNavierStokesSolver,
    KOmegaSST,
    KOmegaSSTModelConstants,
    LinearSolver,
    NavierStokesSolver,
    NoneSolver,
    PressureCorrectionSolver,
    SpalartAllmaras,
    SpalartAllmarasModelConstants,
)
from .component.flow360_params.time_stepping import (
    AdaptiveCFL,
    RampCFL,
    SteadyTimeStepping,
    TimeStepping,
    UnsteadyTimeStepping,
)
from .component.flow360_params.turbulence_quantities import TurbulenceQuantities
from .component.flow360_params.unit_system import (
    CGS_unit_system,
    SI_unit_system,
    UnitSystem,
    flow360_unit_system,
    imperial_unit_system,
)
from .component.flow360_params.volume_zones import (
    FluidDynamicsVolumeZone,
    HeatTransferVolumeZone,
    InitialConditionHeatTransfer,
    PorousMediumVolumeZone,
    ReferenceFrame,
    ReferenceFrameDynamic,
    ReferenceFrameExpression,
    ReferenceFrameOmegaDegrees,
    ReferenceFrameOmegaRadians,
)
from .component.folder import Folder
from .component.meshing.params import (
    Aniso,
    BoxRefinement,
    CylinderRefinement,
    Edges,
    Face,
    Faces,
    Farfield,
    ProjectAniso,
    RotorDisk,
    SurfaceMeshingParams,
    UseAdjacent,
    Volume,
    VolumeMeshingParams,
)
from .component.surface_mesh import SurfaceMesh
from .component.surface_mesh import SurfaceMeshList as MySurfaceMeshes
from .component.volume_mesh import VolumeMesh
from .component.volume_mesh import VolumeMeshList as MyVolumeMeshes
from .environment import Env
from .flags import Flags
from .user_config import UserConfig
from .version import __version__

__all__ = [
    "Accounts",
    "ActuatorDisk",
    "AdaptiveCFL",
    "AeroacousticOutput",
    "AirDensityTemperature",
    "AirPressureTemperature",
    "Aniso",
    "BETDisk",
    "BETDiskChord",
    "BETDiskSectionalPolar",
    "BETDiskTwist",
    "Boundaries",
    "BoxRefinement",
    "CGS_unit_system",
    "Case",
    "CylinderRefinement",
    "Edges",
    "Env",
    "ExpressionInitialCondition",
    "Face",
    "Faces",
    "Farfield",
    "Flags",
    "Flow360MeshParams",
    "Flow360Params",
    "FluidDynamicsVolumeZone",
    "Folder",
    "ForcePerArea",
    "FreestreamBoundary",
    "FreestreamFromMach",
    "FreestreamFromMachReynolds",
    "FreestreamFromVelocity",
    "FreestreamInitialCondition",
    "Geometry",
    "HeatEquationSolver",
    "HeatFluxWall",
    "HeatTransferVolumeZone",
    "IncompressibleNavierStokesSolver",
    "InitialConditionHeatTransfer",
    "IsoSurfaceOutput",
    "IsoSurfaces",
    "IsothermalWall",
    "KOmegaSST",
    "KOmegaSSTModelConstants",
    "LinearSolver",
    "MassInflow",
    "MassOutflow",
    "MeshBoundary",
    "ModifiedRestartSolution",
    "MonitorOutput",
    "Monitors",
    "MyCases",
    "MySurfaceMeshes",
    "MyVolumeMeshes",
    "NavierStokesSolver",
    "NoSlipWall",
    "NoneSolver",
    "PorousMediumBox",
    "PorousMediumVolumeZone",
    "PressureCorrectionSolver",
    "PressureOutflow",
    "ProbeMonitor",
    "ProgressCallbackInterface",
    "ProjectAniso",
    "RampCFL",
    "ReferenceFrame",
    "ReferenceFrameDynamic",
    "ReferenceFrameExpression",
    "ReferenceFrameOmegaDegrees",
    "ReferenceFrameOmegaRadians",
    "RiemannInvariant",
    "RotationallyPeriodic",
    "RotorDisk",
    "SI_unit_system",
    "Slice",
    "SliceOutput",
    "Slices",
    "SlidingInterface",
    "SlidingInterfaceBoundary",
    "SlipWall",
    "SolidAdiabaticWall",
    "SolidIsothermalWall",
    "SpalartAllmaras",
    "SpalartAllmarasModelConstants",
    "SteadyTimeStepping",
    "SubsonicInflow",
    "SubsonicOutflowMach",
    "SubsonicOutflowPressure",
    "SupersonicInflow",
    "SurfaceIntegralMonitor",
    "SurfaceMesh",
    "SurfaceMeshingParams",
    "SurfaceOutput",
    "Surfaces",
    "SymmetryPlane",
    "TimeStepping",
    "TransitionModelSolver",
    "TranslationallyPeriodic",
    "TurbulenceQuantities",
    "UnitSystem",
    "UnsteadyTimeStepping",
    "UnvalidatedFlow360Params",
    "UseAdjacent",
    "UserConfig",
    "UserDefinedDynamic",
    "VelocityInflow",
    "Volume",
    "VolumeMesh",
    "VolumeMeshingParams",
    "VolumeOutput",
    "VolumeZones",
    "WallFunction",
    "ZeroFreestream",
    "ZeroFreestreamFromVelocity",
    "__version__",
    "air",
    "flow360",
    "flow360_unit_system",
    "global_exception_handler",
    "imperial_unit_system",
    "meshing",
    "os",
    "pi",
    "solvers",
    "units",
]
