"""
group_faces_and_run.py - Test face grouping workflow for Flow360 Python UI

Success criterion: all tests pass once the hierarchical navigation and face
grouping API is implemented in flow360.component.geometry.

Mirrors the testing logic from mvp_networkx_geometry/test_geometry.py,
adapted for the Flow360 Python UI.

Uses the real airplane geometry from geometryHierarchicalMetadata.json
(generated by processing Solid-Body-RC-Plane_v2024_colored.SLDPRT).

Run with: python -m pytest group_faces_and_run.py -v
"""

import json
from pathlib import Path
import pytest
import flow360 as fl
fl.Env.load("on_premises").active()
from fl.component.geometry import Geometry, NodeSet, FaceGroup, Node


# ================================================================
# Test Data - Real Aircraft Geometry (Solid-Body-RC-Plane)
# ================================================================

# Expected face counts by colorRGB (from the real geometry)
COLOR_FACE_COUNTS = {
    "0,255,0": 37,     # Green  (leftWing)
    "0,0,255": 37,     # Blue   (rightWing)
    "255,255,0": 27,   # Yellow (leftHorizontalTail)
    "0,255,255": 27,   # Cyan   (rightHorizontalTail)
    "255,0,255": 40,   # Magenta (verticalTail)
}

# Faces with no color or black color form the "remaining" group
REMAINING_FACE_COUNT = 26  # 24 empty-color + 2 black (0,0,0)
TOTAL_FACE_COUNT = 194


# ================================================================
# Fixtures
# ================================================================

@pytest.fixture
def geometry():
    return Geometry("./Solid-Body-RC-Plane_v2024_colored.SLDPRT")


# ================================================================
# Basic Tests
# ================================================================

class TestGeometryBasics:
    """Test basic Geometry functionality."""

    def test_load_from_dict(self, geometry):
        """Test loading from dictionary."""
        assert len(geometry.faces()) == TOTAL_FACE_COUNT

    def test_repr(self, geometry):
        """Test string representation."""
        repr_str = repr(geometry)
        assert "Geometry" in repr_str
        assert "faces" in repr_str

    def test_all_faces_have_uuid(self, geometry):
        """Test that every face node has a _Flow360UUID."""
        for face in geometry.faces():
            assert face.uuid is not None, f"Face '{face.name}' is missing _Flow360UUID"


# ================================================================
# Navigation Tests
# ================================================================

class TestNavigation:
    """Test tree navigation methods."""

    def test_root_node(self, geometry):
        """Test getting root node."""
        root = geometry.root_node()
        assert len(root) == 1
        # geometry.children() is equivalent to geometry.root_node().children()
        assert geometry.children() == geometry.root_node().children()

    def test_root_is_model_file(self, geometry):
        """Test that root node is a ModelFile."""
        root_node = next(iter(geometry.root_node()))
        assert root_node.type == "ModelFile"
        assert root_node.name == "Solid-Body-RC-Plane_v2024_colored"

    def test_children(self, geometry):
        """Test getting direct children of root."""
        children = geometry.children()
        assert len(children) == 1  # One top-level Assembly
        node = next(iter(children))
        assert node.type == "Assembly"

    def test_children_with_filter(self, geometry):
        """Test filtering children by type."""
        assemblies = geometry.children(type="Assembly")
        assert len(assemblies) == 1

        # No Part directly under root
        parts = geometry.children(type="Part")
        assert len(parts) == 0

    def test_descendants(self, geometry):
        """Test getting all descendants."""
        all_nodes = geometry.descendants()
        # ModelFile > Assembly > Assembly > Part > Body > ShellCollection > Shell
        # + 194 faces + 3 BodyCollections = many nodes
        assert len(all_nodes) > 200

    def test_descendants_with_filter(self, geometry):
        """Test filtering descendants by type."""
        faces = geometry.descendants(type="Face")
        assert len(faces) == TOTAL_FACE_COUNT

        assemblies = geometry.descendants(type="Assembly")
        assert len(assemblies) == 2  # Two nested Assemblies

        parts = geometry.descendants(type="Part")
        assert len(parts) == 1

        shells = geometry.descendants(type="Shell")
        assert len(shells) == 1

        body_collections = geometry.descendants(type="BodyCollection")
        assert len(body_collections) == 3  # Sketch1, Sketch2, Sketch3

    def test_chained_descendants_with_faces(self, geometry):
        """Test that chained descendants produce the same face set."""
        assert geometry.descendants(type="Face") == geometry.descendants().descendants(type="Face")

    def test_chained_navigation(self, geometry):
        """Test chaining navigation methods."""
        # Root > Assembly > Assembly (2 levels deep)
        grandchildren = geometry.children().children()
        assert len(grandchildren) == 1  # "Default" Assembly
        node = next(iter(grandchildren))
        assert node.name == "Default"
        assert node.type == "Assembly"

    def test_faces_shortcut(self, geometry):
        """Test that faces() is equivalent to descendants(type='Face')."""
        assert geometry.faces() == geometry.descendants(type="Face")

    def test_descendants_by_name(self, geometry):
        """Test filtering descendants by name glob pattern."""
        sketches = geometry.descendants(name="Sketch*")
        assert len(sketches) == 3  # Sketch1, Sketch2, Sketch3

        default = geometry.descendants(name="Default")
        assert len(default) == 1


# ================================================================
# Faces Method Tests
# ================================================================

class TestFaces:
    """Test faces() method functionality."""

    def test_faces_total(self, geometry):
        """Test getting all faces."""
        faces = geometry.faces()
        assert len(faces) == TOTAL_FACE_COUNT

    def test_faces_by_color(self, geometry):
        """Test filtering faces by colorRGB."""
        for color, expected_count in COLOR_FACE_COUNTS.items():
            faces = geometry.faces(colorRGB=color)
            assert len(faces) == expected_count, (
                f"colorRGB={color}: expected {expected_count}, got {len(faces)}"
            )

    def test_faces_black(self, geometry):
        """Test filtering black faces."""
        black_faces = geometry.faces(colorRGB="0,0,0")
        assert len(black_faces) == 2

    def test_faces_no_color(self, geometry):
        """Test filtering faces with empty colorRGB."""
        # Faces with empty string color
        empty_color_faces = geometry.faces(colorRGB="")
        assert len(empty_color_faces) == 24

    def test_faces_color_glob(self, geometry):
        """Test filtering faces by colorRGB with glob pattern."""
        # All faces where red channel is 255
        red_channel_faces = geometry.faces(colorRGB="255,*")
        # 255,255,0 (27) + 255,0,255 (40) = 67
        assert len(red_channel_faces) == 67

    def test_faces_under_assembly(self, geometry):
        """Test getting faces under a specific assembly node."""
        default_assembly = geometry.descendants(name="Default", type="Assembly")
        assert len(default_assembly) == 1

        faces_under = default_assembly.faces()
        assert len(faces_under) == TOTAL_FACE_COUNT  # All faces are under Default

    def test_faces_under_shell(self, geometry):
        """Test getting faces under Shell node."""
        shell = geometry.descendants(type="Shell")
        assert len(shell) == 1

        shell_faces = shell.faces()
        assert len(shell_faces) == TOTAL_FACE_COUNT  # All 194 faces under the single Shell

    def test_faces_with_attribute_filter(self, geometry):
        """Test filtering faces by nested attribute."""
        # All faces have _Flow360UUID in attributes
        # Filtering by a specific UUID should return exactly 1 face
        sample_face = next(iter(geometry.faces()))
        uuid = sample_face.uuid
        matched = geometry.faces(attributes={"_Flow360UUID": uuid})
        assert len(matched) == 1


# ================================================================
# NodeSet Set Operations Tests
# ================================================================

class TestNodeSetOperations:
    """Test NodeSet set operations."""

    def test_union(self, geometry):
        """Test union of selections."""
        green = geometry.faces(colorRGB="0,255,0")
        blue = geometry.faces(colorRGB="0,0,255")
        combined = green | blue
        assert len(combined) == 37 + 37

    def test_intersection(self, geometry):
        """Test intersection of selections."""
        green = geometry.faces(colorRGB="0,255,0")
        blue = geometry.faces(colorRGB="0,0,255")
        common = green & blue
        assert len(common) == 0  # No face is both green and blue

    def test_difference(self, geometry):
        """Test difference of selections."""
        all_faces = geometry.faces()
        green = geometry.faces(colorRGB="0,255,0")
        remaining = all_faces - green
        assert len(remaining) == TOTAL_FACE_COUNT - 37

    def test_union_covers_all_colored(self, geometry):
        """Test that union of all color groups covers the colored faces."""
        combined = NodeSet(geometry, geometry._backend, set())
        for color in COLOR_FACE_COUNTS:
            combined = combined | geometry.faces(colorRGB=color)
        assert len(combined) == sum(COLOR_FACE_COUNTS.values())  # 168


# ================================================================
# Face Group Tests
# ================================================================

class TestFaceGroups:
    """Test FaceGroup creation and management."""

    def test_create_group_by_color(self, geometry):
        """Test creating a face group filtered by colorRGB."""
        green = geometry.create_face_group(
            name="leftWing",
            selection=geometry.faces(colorRGB="0,255,0")
        )
        assert green.name == "leftWing"
        assert green.face_count() == 37

    def test_list_groups(self, geometry):
        """Test listing groups."""
        geometry.create_face_group(
            name="leftWing",
            selection=geometry.faces(colorRGB="0,255,0")
        )
        geometry.create_face_group(
            name="rightWing",
            selection=geometry.faces(colorRGB="0,0,255")
        )
        groups = geometry.list_groups()
        assert "leftWing" in groups
        assert "rightWing" in groups

    def test_get_group(self, geometry):
        """Test getting group by name."""
        geometry.create_face_group(
            name="leftWing",
            selection=geometry.faces(colorRGB="0,255,0")
        )
        group = geometry.get_face_group("leftWing")
        assert group.name == "leftWing"
        assert group.face_count() == 37

    def test_duplicate_group_raises(self, geometry):
        """Test that duplicate group names raise error."""
        geometry.create_face_group(
            name="leftWing",
            selection=geometry.faces(colorRGB="0,255,0")
        )
        with pytest.raises(ValueError):
            geometry.create_face_group(
                name="leftWing",
                selection=geometry.faces(colorRGB="0,0,255")
            )

    def test_clear_groups(self, geometry):
        """Test clearing all groups."""
        geometry.create_face_group(
            name="leftWing",
            selection=geometry.faces(colorRGB="0,255,0")
        )
        geometry.clear_groups()
        assert len(geometry.list_groups()) == 0

    def test_face_moves_to_new_group(self, geometry):
        """Test that a face is removed from its old group when assigned to a new one."""
        # Create a group with all faces
        everything = geometry.create_face_group(
            name="everything",
            selection=geometry.faces()
        )
        assert everything.face_count() == TOTAL_FACE_COUNT

        # Create a new group that takes the green faces (37 of 194)
        green = geometry.create_face_group(
            name="green",
            selection=geometry.faces(colorRGB="0,255,0")
        )
        assert green.face_count() == 37
        # "everything" should lose those 37 faces
        assert everything.face_count() == TOTAL_FACE_COUNT - 37

    def test_face_reassignment_empties_old_group(self, geometry):
        """Test that reassigning all faces from a group leaves it empty."""
        green = geometry.create_face_group(
            name="groupA",
            selection=geometry.faces(colorRGB="0,255,0")
        )
        assert green.face_count() == 37

        # Create another group with the same faces
        green2 = geometry.create_face_group(
            name="groupB",
            selection=geometry.faces(colorRGB="0,255,0")
        )
        assert green2.face_count() == 37
        assert green.face_count() == 0  # All faces moved to groupB

    def test_no_double_counting_in_total(self, geometry):
        """Test that total faces across all groups never exceeds geometry face count."""
        geometry.create_face_group(
            name="green",
            selection=geometry.faces(colorRGB="0,255,0")
        )
        # Green and blue overlap with "all faces" but exclusive ownership prevents duplication
        geometry.create_face_group(
            name="blue",
            selection=geometry.faces(colorRGB="0,0,255")
        )
        geometry.create_face_group(
            name="rest",
            selection=geometry.faces()
        )

        total = sum(
            geometry.get_face_group(name).face_count()
            for name in geometry.list_groups()
        )
        assert total == TOTAL_FACE_COUNT


# ================================================================
# Full Airplane Grouping Workflow Tests
# ================================================================

class TestAirplaneGroupingWorkflow:
    """Test the complete airplane face grouping workflow (mirrors the web UI test)."""

    def test_full_color_grouping_workflow(self, geometry):
        """
        Test the exact workflow performed in the browser:
        create 5 groups by color, then group remaining faces.
        """
        # Step 1: leftWing (Green)
        left_wing = geometry.create_face_group(
            name="leftWing",
            selection=geometry.faces(colorRGB="0,255,0")
        )
        assert left_wing.face_count() == 37

        # Step 2: rightWing (Blue)
        right_wing = geometry.create_face_group(
            name="rightWing",
            selection=geometry.faces(colorRGB="0,0,255")
        )
        assert right_wing.face_count() == 37

        # Step 3: leftHorizontalTail (Yellow)
        left_h_tail = geometry.create_face_group(
            name="leftHorizontalTail",
            selection=geometry.faces(colorRGB="255,255,0")
        )
        assert left_h_tail.face_count() == 27

        # Step 4: rightHorizontalTail (Cyan)
        right_h_tail = geometry.create_face_group(
            name="rightHorizontalTail",
            selection=geometry.faces(colorRGB="0,255,255")
        )
        assert right_h_tail.face_count() == 27

        # Step 5: verticalTail (Magenta)
        vertical_tail = geometry.create_face_group(
            name="verticalTail",
            selection=geometry.faces(colorRGB="255,0,255")
        )
        assert vertical_tail.face_count() == 40

        # Verify intermediate state: 168 assigned, 26 unassigned
        assigned = sum(g.face_count() for g in [
            left_wing, right_wing, left_h_tail, right_h_tail, vertical_tail
        ])
        assert assigned == 168

        # Step 6: Remaining faces (fuselage — empty/black color)
        remaining = geometry.create_face_group(
            name="fuselage",
            selection=(geometry - left_wing - right_wing
                       - left_h_tail - right_h_tail - vertical_tail)
        )
        assert remaining.face_count() == REMAINING_FACE_COUNT

        # Verify complete coverage
        total = sum(
            geometry.get_face_group(name).face_count()
            for name in geometry.list_groups()
        )
        assert total == TOTAL_FACE_COUNT
        assert len(geometry.list_groups()) == 6

    def test_group_all_then_split(self, geometry):
        """Test grouping all faces first, then splitting into color groups."""
        # Start with everything in one group
        everything = geometry.create_face_group(
            name="everything",
            selection=geometry.faces()
        )
        assert everything.face_count() == TOTAL_FACE_COUNT

        # Split out each color group — "everything" shrinks each time
        for name, color in [
            ("leftWing", "0,255,0"),
            ("rightWing", "0,0,255"),
            ("leftHorizontalTail", "255,255,0"),
            ("rightHorizontalTail", "0,255,255"),
            ("verticalTail", "255,0,255"),
        ]:
            geometry.create_face_group(
                name=name,
                selection=geometry.faces(colorRGB=color)
            )

        # "everything" should now contain only the remaining 26 faces
        assert everything.face_count() == REMAINING_FACE_COUNT


# ================================================================
# Remaining Faces Pattern Tests
# ================================================================

class TestRemainingFacesPattern:
    """Test the 'remaining faces' pattern with subtraction."""

    def test_geometry_minus_group(self, geometry):
        """Test subtracting group from geometry."""
        green = geometry.create_face_group(
            name="green",
            selection=geometry.faces(colorRGB="0,255,0")
        )
        remaining = geometry - green
        assert len(remaining) == TOTAL_FACE_COUNT - 37

    def test_chained_subtraction(self, geometry):
        """Test subtracting multiple groups."""
        green = geometry.create_face_group(
            name="green",
            selection=geometry.faces(colorRGB="0,255,0")
        )
        blue = geometry.create_face_group(
            name="blue",
            selection=geometry.faces(colorRGB="0,0,255")
        )
        remaining = geometry - green - blue
        assert len(remaining) == TOTAL_FACE_COUNT - 37 - 37


# ================================================================
# NodeSet Tests
# ================================================================

class TestNodeSet:
    """Test NodeSet functionality."""

    def test_len(self, geometry):
        """Test len() on NodeSet."""
        children = geometry.children()
        assert len(children) == 1  # One top-level Assembly

        parts = geometry.descendants(type="Part")
        assert len(parts) == 1

    def test_empty_nodeset(self, geometry):
        """Test empty NodeSet behavior."""
        empty = geometry.children(name="NonExistent")
        assert len(empty) == 0
        assert not empty  # Should be falsy
        assert empty.is_empty()


# ================================================================
# Node Tests
# ================================================================

class TestNode:
    """Test Node class functionality."""

    def test_iterate_returns_nodes(self, geometry):
        """Test that iterating NodeSet yields Node objects."""
        for node in geometry.descendants(type="Assembly"):
            assert isinstance(node, Node)

    def test_node_attributes(self, geometry):
        """Test Node attribute access."""
        root = next(iter(geometry.root_node()))
        assert root.type == "ModelFile"
        assert root.name == "Solid-Body-RC-Plane_v2024_colored"

    def test_node_uuid(self, geometry):
        """Test Node UUID access for face nodes."""
        faces = list(geometry.faces())
        assert len(faces) == TOTAL_FACE_COUNT

        for face in faces[:5]:  # Check first 5 faces
            assert face.uuid is not None
            assert face.is_face()

    def test_node_navigation(self, geometry):
        """Test navigation from individual Node."""
        # Get the single Part node
        part = next(iter(geometry.descendants(type="Part")))
        assert part.type == "Part"

        # Navigate to children (Body + 3 BodyCollections)
        children = part.children()
        assert len(children) == 4

        # Navigate to faces (should find all 194 faces deep in hierarchy)
        faces = part.faces()
        assert len(faces) == TOTAL_FACE_COUNT

    def test_node_equality(self, geometry):
        """Test Node equality comparison."""
        assemblies1 = list(geometry.descendants(type="Assembly"))
        assemblies2 = list(geometry.descendants(type="Assembly"))

        for n1, n2 in zip(sorted(assemblies1, key=lambda n: n.name),
                         sorted(assemblies2, key=lambda n: n.name)):
            assert n1 == n2

    def test_node_in_nodeset(self, geometry):
        """Test Node containment in NodeSet."""
        faces = geometry.faces()
        node = next(iter(faces))
        assert node in faces

    def test_face_node_color(self, geometry):
        """Test that face nodes expose colorRGB via the color property."""
        green_faces = geometry.faces(colorRGB="0,255,0")
        for face in green_faces:
            assert face.color == "0,255,0"


# ================================================================
# Run Tests
# ================================================================

if __name__ == "__main__":
    pytest.main([__file__, "-v"])
