# Used to automatically create a pull request with updated schemas

name: Automatic schema update

on:
  push:
    paths:
      - tools/integrations/data/**

permissions:
    contents: write

jobs:
  schema-update:
    runs-on: ubuntu-latest
    steps:

    # Checkout the Flow360 project 
    - name: Checkout python client repo
      uses: actions/checkout@v3
      with:
        path: develop
    
    # Check if python client directory has changed 
    - name: Check if JSON schema files have changed
      id: schema-changed
      uses: tj-actions/changed-files@v42
      with:
        files: "tools/integrations/data/"

    # Checkout the Flow360WebClient project
    - name: Checkout web client repo
      if: steps.schema-changed.any_changed == 'true'
      uses: actions/checkout@v3
      with:
        repository: flexcompute/Flow360WebClient
        path: schema-auto-update
        fetch-depth: 0

    # Update schema branch with develop
    - name: Update schema branch
      if: steps.schema-changed.any_changed == 'true'
      run: |
        cd Flow360WebClient
        git checkout develop
        git fetch origin
        git checkout schema-auto-update
        git pull
        git merge origin/develop
        git push -f origin schema-auto-update

    # Copy schema files to the target folder in webclient repo
    - name: Copy files from Flow360 repo to WebClient repo
      if: steps.schema-changed.any_changed == 'true'
      run: |
        cp -a tools/integrations/data/. Flow360WebClient/src/components/FormGenerator/schemas/case/
        cd Flow360WebClient
        git add Flow360WebClient/src/components/FormGenerator/schemas/case/
        git commit -m "Automatic schema update"
        git push -f
        
