# Used to automatically create a pull request with updated schemas
name: Automatic schema update

on:
  push:
    branches:
      - 'develop'
      - 'auto-schema-update-test'
    paths:
      - 'tools/integrations/data/**'

jobs:
  schema-update:
    runs-on: ubuntu-latest
    steps:

    # Checkout the Flow360 project
    - name: Checkout python client repo
      uses: actions/checkout@v4
      with:
        ref: develop
        path: Flow360
        fetch-depth: 0

    # Checkout Flow360WebClient project
    - name: Checkout web client repo
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.AUTOMATION_TEST_TOKEN }}
        ref: schema-auto-update
        path: Flow360WebClient
        fetch-depth: 0
        repository: 'flexcompute/Flow360WebClient'